### ISSUE TITLE
Allow to extend BaseFormatter outside of AMD

### ISSUE THREAD

**Issue by aryelu** [benjamine/jsondiffpatch#100]
I'd like to extend BaseFormatter without adding support for AMD to my project.
I think you should add the `BaseFormatter` to `index.js` in `formatters` library:
```js
exports.base = require('./base');
```

**Comment by benjamine** [comment]
makes sense, I would try to keep the library API as narrow as possible to avoid breaking compatibility but I guess that base formatter is already stable enough.

**Comment by benjamine** [comment]
fixed in jsondiffpatch@0.1.34
