### ISSUE TITLE
JSON Path

### ISSUE THREAD

**Issue by kazoompa** [benjamine/jsondiffpatch#102]
Wouldn't it be useful to have JSON paths pointing to individual diffs? This prevents traversing a tree to find the changed element. Just an idea.

**Comment by benjamine** [comment]
both approaches have pros and cons, using paths (like the JSON Patch format does) means that having many changes in a deep branch the path has to be repeated many times. Also, the nested object format has the advantage of looking closer to the original object.
Finally, it should be trivial to convert to a format using paths, in fact, creating a formatter for JSON Patch is on my plans, it's a common request.
