### ISSUE TITLE
Refactor dynamic require statements

### ISSUE THREAD

**Issue by glf256** [benjamine/jsondiffpatch#107]
Anything along the lines of:

```
var dynamicRequire = ...;
var resultingModule = require(dynamicRequire);
```

Unless this is an artifact of the build process, it seems to me that it is unnecessary and breaks software like [crcn/nexe](https://github.com/crcn/nexe).

**Comment by benjamine** [comment]
yes, it is intentional for the build process, basically this makes browserify to not bundle that dependency, so it's used for any dependency that I don't want in the main browser bundle.
there are other similar issues reported, but unfortunately, I think I haven't yet seen a nice solution that can make all bundling tools/module systems happy.
I would be very happy if we can find it.

**Comment by gregoryfabry** [comment]
Would explicitly excluding those modules in your browserify configuration work? https://github.com/substack/node-browserify#bexcludefile

**Comment by benjamine** [comment]
it could be better, but one problem I see with that is, that won't work for people using this is as a dependency, browserify config is not inherited (I wish browserify supported inline comments for this stuff, like jshint for example)

**Comment by gaearon** [comment]
This also causes warnings like this in dependent libraries with Webpack.

<img width="448" alt="screen shot 2016-02-23 at 13 48 48" src="https://cloud.githubusercontent.com/assets/810438/13253573/a7b9b3fe-da34-11e5-924d-cc39bbcf7554.png">

One way to fix this would be to refactor env-specific modules to be functions accepting `isClientSide` as an argument. Then you would be able to use `browser` field in package.json (respected by all major bundlers) to “remap” these files to browser versions that inject `true` there.

You can see this technique in action [here](https://github.com/kriskowal/asap/blob/d7359b771fb3ff41f8bfcbb1fa00ade7126fc622/package.json#L19-L23).

**Comment by benjamine** [comment]
thanks @gaearon I want to do some refactor on the bundling process, but yes I've been looking to have a mechandism that makes at least browserify and webpack happy, I'm just not familiar with webpack, but package json `browser` is something respect (even when entering into dependencies) that might be the perfect solution.

**Comment by gaearon** [comment]
>if package.json browser is something both respect (even when entering into dependencies) that might be the perfect solution.

I can confirm this is the case.

**Comment by benjamine** [comment]
awesome!, pasting this here for reference https://github.com/defunctzombie/package-browser-field-spec

**Comment by Methuselah96** [comment]
I believe [this has been resolved](https://github.com/benjamine/jsondiffpatch/issues/76#issuecomment-380086881).
