### ISSUE TITLE
Source maps in non-minified build code messes up chrome dev tools

### ISSUE THREAD

**Issue by nbrustein** [benjamine/jsondiffpatch#110]
When I used `jsondiffpatch/public/build/jsondiffpatch-full.js` for local development, I started to have problems with chrome devtools.  If I put a debugger in my own code, then in the source tab of the chrome devtools I would end up in this file: `jsondiffpatch/src/formatters/index.js`

When I switched to using the minified files for local development, like  `jsondiffpatch/public/build/jsondiffpatch-full.min.js`, the problem went away.

Maybe remove the sourcemap stuff from the distributed .js files?

**Comment by Methuselah96** [comment]
Hello, sorry for the delayed response!

The builds have been changed quite a bit since this issue was filed, is this still an issue for you?
