### ISSUE TITLE
Uncaught Error: functions are not supported

### ISSUE THREAD

**Issue by sjoerd222888** [benjamine/jsondiffpatch#112]
When there are functions in the objects you try to diff you get `Uncaught Error: functions are not supported`. If I now want to build a filter that simply ignores items of type function I have tried the following:

    var functionDiffFilter = function(context) {
        if (typeof context.left === 'function' || typeof context.right === 'function' ) {
            context.exit();
        }
    };

Is this the correct way to completely ignore variables of type function?

**Comment by benjamine** [comment]
almost, you also need to set the diff result to `undefined` (ie. no diff)
``` js
var jdp = jsondiffpatch.create();
jdp.processor.pipes.diff.before('trivial', function ignoreFunctionDiffFilter(context) {
    if (typeof context.left === 'function' || typeof context.right === 'function' ) {
        context.setResult(undefined);
        context.exit();
    }
});

console.log(jdp.diff({  fn: setTimeout }, { fn: setInterval })); // logs undefined
```

**Comment by sjoerd222888** [comment]
Thx!

**Comment by nonoroazoro** [comment]
@benjamine  Can I use the `propertyFilter` option to ignore the functions?

```javascript
{
    propertyFilter(name: string, context: any)
    {
        // Ignore function properties.
        return !isFunction(context.left[name]) && !isFunction(context.right[name]);
    }
}
```
