### ISSUE TITLE
Diff reorder array

### ISSUE THREAD

**Issue by olafura** [benjamine/jsondiffpatch#114]
When you have two json docs like these:
{"1": [1,2,3]}
{"1": [3,2,1]}

jsondiffpatch gives me:
{"1": {"_1": ["", 1, 3], "_2": ["", 0, 3], "_t": "a"}}

But the library I made to replicate the diff format[1], creates this:
{"1": {"_0": ["", 2, 3], "_2" : ["", 0, 3], "_t": "a"}}

But give the exact same result when you use patch but I don't
know how to interpreted the result given by jsondiffpatch, my
first reacting was that it must be a bug.

[1] https://github.com/olafura/json_diff_ex

**Comment by benjamine** [comment]
array diffing is explained at https://github.com/benjamine/jsondiffpatch/blob/master/docs/arrays.md
and here's the doc to understand what the diff means https://github.com/benjamine/jsondiffpatch/blob/master/docs/deltas.md#array-with-inner-changes

multiple possible deltas can be valid for the same left/right arrays (as your example proves).
both are valid, and jsondiffpatch (and your implemenation) I presume are compatible with both, ie. you could use that patch you got with jsondiffpatch and it will work fine.

so, in theory this incongruence shouldn't matter. but, why are they different?
I'm not sure how json_diff_ex is implemented but I suppose it could be a difference in how LCS and the move detection are implemented (different implementations are possible).
eg. this is jsondiffpatch implementation of LCS: https://github.com/benjamine/jsondiffpatch/blob/master/src/filters/lcs.js
