### ISSUE TITLE
Array diff includes extensions to the Array prototype 

### ISSUE THREAD

**Issue by AlexMedia** [benjamine/jsondiffpatch#117]
I have a project where a few functions have been added to `Array.prototype`. When I have two objects that I want to run a diff against, jsondiffpatch returns me the array with a couple of `NaN` keys added to the bottom, without any values. The amount of `NaN`s is equal to the amount of functions which were added to the prototype.

I made a sample JSFiddle which [can be viewed here](http://jsfiddle.net/AlexMedia/h0y8hwe6/).

I would suggest that these items do not show up in the diff, as these functions are not part of the array but instead of its prototype. I believe that using `array.hasOwnProperty(key)` could be used to exclude prototype extensions, but I'm still trying to figure out how array diffing works internally.

**Comment by Syzygy24** [comment]
Having some trouble with this as well. A temporary workaround is that you can set showUnchanged to false and it ignores the ```Array.prototype``` field, because the prototypes don't change.

**Comment by benjamine** [comment]
fixed (the problem was on the formatter, deltas were correct), released as 0.2.3 , thanks for the detailed report!
