### ISSUE TITLE
Use with typescript projects

### ISSUE THREAD

**Issue by episodeyang** [benjamine/jsondiffpatch#118]
Just wondering, has anyone used this with a typescript project?

**Comment by inakianduaga** [comment]
[Yes, WIP](https://github.com/inakianduaga/redux-state-history/blob/master/src/Middleware.ts). There is nothing special about typescript that would not let you use this.

**Comment by episodeyang** [comment]
this is great! I just got my angular2 tool chain to work. Will probably be ready when you are done.

**Comment by episodeyang** [comment]
btw, I just published this: https://github.com/escherpad/luna in case it is useful.

**Comment by benjamine** [comment]
cool, thanks @inakianduaga, as far as I know, typescript is a superset of js, so every js library should work with typescript
