### ISSUE TITLE
Ignore all keys of a particular parent

### ISSUE THREAD

**Issue by dbainbridge** [benjamine/jsondiffpatch#120]
I'm trying to ignore diffing all keys under a particular parent so that I don't have to specify each key name under this parent.  I'm adding a filter with
```javascript
jsondiffpatch.processor.pipes.diff.before
```
I can not however figure out how to correctly specify this. i.e. Ignore any keys with parent "metaData".
```
{
  "val1" : 667,
  "val2" : 375,
  "metaData" : {
    "x" : 50,
    "y" : 51
  }
}

**Comment by dbainbridge** [comment]
https://github.com/benjamine/jsondiffpatch/pull/105 Addresses this issue.  Simple enough code addition hope it can be integrated.

**Comment by benjamine** [comment]
I added support for a propertyFilter option ( see https://github.com/benjamine/jsondiffpatch#options ), 
this function receives a property name, and context object which you can use to filter not only by property name, but also by looking at parent left of right objects.
