### ISSUE TITLE
Need clarity on whole array diffing/patching

### ISSUE THREAD

**Issue by brandonros** [benjamine/jsondiffpatch#126]
I am using jsondiffpatch in a web service at the moment, and users are complaining about duplicates in their arrays.

The only point of patch creation I am doing is currently this: `var delta = jsondiffpatch.diff(old_elements, new_elements);`

I read the documentation about LCS, then the fallback to position. Do I need to do anything special? What information can I provide? I'm sure it isn't a bug and something on my end.

**Comment by brandonros** [comment]
Does LCS start going through every array in an object, or just the root objects in the supplied array itself?

**Comment by brandonros** [comment]
LCS was traversing all arrays in an object, so I dummied out and just sorted the array pre-diff. I was experiencing duplicates before hand. Not sure if this is a bug or an error on my half.

**Comment by benjamine** [comment]
hi brandon, what would allow to find the issue on jsondiffpatch is a way to reproduce it, which in this case is rather simple (if you can isolate them), a set of: parameters (left value, right value, options), result and expected result.

**Comment by brandonros** [comment]
@benjamine 

```
var a = [{
	id: '1',
	moo: [{
		'b': 123
	}]
}];

var b = [{
	id: '1',
	moo: [{
		'b': 123
	}]
}];

var diffpatcher = jsondiffpatch.create({
	objectHash: function (obj) {
		return obj['id'].toString();
	}
});

console.log(diffpatcher.diff(a, b));
```

Watch the error thrown. It traverses into a.moo and b.moo.

**Comment by benjamine** [comment]
thanks!, and yes, that's expected behavior, a[0] and b[0] where detected to be the same object (same id), so it proceeded to diff inside the object to see if/how it changed, I'd use an objectHash function that can obtain a hash for any array item in the diffed objects, examples:
``` js
function objectHash(obj, index) {
  return obj.id || ('index:' + index);
}
function objectHash(obj) {
  return obj.id || JSON.stringify(obj);
}
function objectHash(obj, index) {
  return obj.id || obj.b;
}
```

(this doesn't seem to be related to creating duplicates)

**Comment by brandonros** [comment]
@benjamine I resorted to sorting all arrays before diffing. Is this the equivalent of using JSON.stringify(obj) for the hasher?

I can't recreate the duplication in isolation but have seen multiple instances of it. Any idea what it could be?

**Comment by benjamine** [comment]
using JSON.stringify will only match objects if they're exactly equal (a deep compare), sorting would only affect you if you match them by position (ie. not providing an objectHash, or using the index parameter on it, like in the first example above), the problem of course with match by position is that an insert somewhere in the middle of the array, will mark everything below (that moved 1 position) as removes and adds. So it will be always more efficient to match by id or any other key your objects might have, whenever possible.

re. duplication I'd try to detect that when it happens and log (1-check for duplicates, 2-do your operation (diff, or patch), 3 check for duplicates, if duplicates appeared => log it all), that way you might find examples to reproduce an issue.

**Comment by brandonros** [comment]
I only want to differentiate on top level elements. I've got all different kinds of data that usually is just array contained. I guess I can just make objectHash return the MD5 of the stringified object? Or would that be too computationally expensive?

Duplication: This is actually live on a SaaS platform. I had a user report it, and I popped open her console. I followed it back, but couldn't recreate it given the before, after, and delta. I will try what you suggest. Have you ever seen it before?

**Comment by benjamine** [comment]
I see, yeah MD5 doesn't seem necessary, but I'd the example #1, I put above, ie. use obj.id (which will solve the top-level), and `|| index`, which means, match by position, which is probably the best to do when the data is unpredictable.

honestly I have no context to understand the problem, I don't remember a problem with duplication, but that might mean something totally different in your application, maybe you're applying a patch with an insert twice? but that might be ok in some applications.

**Comment by brandonros** [comment]
I'm really racking my brain here. I've put all kinds of code to sort the elements, as well as remove any duplicates detected, and I still have users telling me they see duplicates.

Maybe you can tell me if my workflow is flawed in some way:

On server, sort elements. Then, compare old version to new version, calculate patch, stringify it and pass it to client.

On client, sort elements, pull up old version, apply patch, store.

**Comment by benjamine** [comment]
that description is not enough to understand what's going on, even less to debug it, even if I wanted.
now, array deltas have index positions on it, if what you're saying is you sort an array between diff and patch, that patch will break things, a patch cannot be applied to a different version of what you diffed without consequences.
my recommendation to detect duplicates was not to remove them, but to log reproduction steps.
without reproduction steps, this is not going anywhere.

**Comment by brandonros** [comment]
I figured out what it is.

I had a Websocket responding to an event that would apply a patch. When having multiple tabs open, there would be multiple websockets affecting the same database twice concurrently.

I've implemented locks, should anybody ever encounter this.

Thank you for the help.

**Comment by brandonros** [comment]
Just to clarify, is it required that the elements be sorted when patching?

**Comment by benjamine** [comment]
yes to apply a patch it needs to be in the same order it was when the patch was created (the patch has references to specific indices in the array).
In general a patch can only applied to an object in the same state as it was when diffed, there is no support yet for something like rebasing or conflict resolution.
If the order is not important/not preserved I'd use an object (with properties as keys).

**Comment by brandonros** [comment]
I am using this to transmit patches over the wire (server -> client), but I feel I get intermittent errors a lot due to this not working, despite sorting.

What can you recommend? Should I try jsonpatch or diff instead?
