### ISSUE TITLE
functions are not supported

### ISSUE THREAD

**Issue by RAKESH1256** [benjamine/jsondiffpatch#133]
got this error 'functions are not supported'

**Comment by benjamine** [comment]
yes, functions are not supported. just as JSON.stringify/parse doesn't.
but you can add support with a plugin if you define a custom way to serialize/deserialize functions into diffs: https://github.com/benjamine/jsondiffpatch/blob/master/docs/plugins.md

**Comment by ccorcos** [comment]
@benjamine seems like it should be possible to handle functions without serializing...

**Comment by ccorcos** [comment]
Ah, this works:

```js
import jsondiffpatch from "jsondiffpatch";

const diffpatcher = jsondiffpatch.create();
diffpatcher.processor.pipes.diff.before("trivial", context => {
  if (
    typeof context.left === "function" || typeof context.right === "function"
  ) {
    context.setResult([context.left, context.right]).exit();
  }
});
```

nice modular design :)
