### ISSUE TITLE
Can we avoid precision diffs using this tool?

### ISSUE THREAD

**Issue by kkagresh** [benjamine/jsondiffpatch#134]
Hi, I am trying to get some understanding of this tool and see if it can fit our needs. Is it possible to avoid diffs with difference in precision. For e.g. there are two values say 1.23456 and 1.23457, can we avoid diff here using this tool as 0.00001 is negligible for our needs?

**Comment by benjamine** [comment]
yes you can use de propertyFilter option, it receives a property name (useless for you) and a context, you can compare context.left[name] to context.right[name] to return a boolean indicating if that property has to be diffed.
the only gotcha is this would work kbly if those numbers are in an object property.
if they're items in an array, you can still do it with a Plugin, see the link in the README for an example, but that's a bit more complicated.

**Comment by kkagresh** [comment]
Can you explain me how should I use propertyFilter? I assume it in following way when I want to avoid comparing performance data
```javascript
var diffPatcher = require(jsondiffpatch').create({
   propertyFilter: function(name){
        return name === 'PerformanceData';
      }
});
```
I get an empty array with this approach. Correct me if I am wrong. Thanks

**Comment by benjamine** [comment]
the function should return `false` for properties you want to ignore, as I mentioned in your case `name` might not be useful, you can use 2nd argument to check left and right values.
```
var diffPatcher = require('jsondiffpatch').create({
  propertyFilter: function(name, context){
    var left = context.left[name], right = context.right[name];
    if (typeof left === 'number' && typeof right === 'number' && Math.abs(left-right) < 0.00001) return false;
    return true;
  }
});
```
