### ISSUE TITLE
Warning when using webpack

### ISSUE THREAD

**Issue by graingert** [benjamine/jsondiffpatch#137]
```
WARNING in ./~/jsondiffpatch/src/main.js
Critical dependencies:
48:20-50 the request of a dependency is an expression
53:19-47 the request of a dependency is an expression
 @ ./~/jsondiffpatch/src/main.js 48:20-50 53:19-47
```

**Comment by vlki** [comment]
Hey! I do enjoy using jsondiffpatch, but the integration with webpack is clumsy when trying to do it without seeing that warning all the time. Any plans to fix it? Is it something I can help with?

**Comment by benjamine** [comment]
yes, #107 mentions a solution that could make happy webpack and browserify (the bundler this project supports), and node.js. closing this one to centralize.

**Comment by ohenrik** [comment]
I can't seem to figure out how to get webpack to play nice and not display these warnings.

It would be great if example of fixes for both webpack and browserify are posted here or added to the documentation.

**Comment by vlki** [comment]
@ohenrik In my webpack config I was successful with loading the built jsonpatchdiff and making sure webpack does not parse it. Like this:
```javascript
{
    module: {
        loaders: [
            // ...
        ],

        noParse: [
            // It is better to load the jsondiffpatch's src files, but there
            // is a problem that it issue warnings when webpack is trying
            // to parse it because of some dynamic requires.
            //
            // Change back to loading source when following get fixed:
            // https://github.com/benjamine/jsondiffpatch/issues/137
            /jsondiffpatch[\/]public[\/]build[\/]jsondiffpatch\.js/
        ]
    },

    resolve: {
        modulesDirectories: [
            'node_modules'
        ],

        alias: {
            jsondiffpatch: 'jsondiffpatch/public/build/jsondiffpatch.js'
        }
    },
}
```
Hope it helps.
