### ISSUE TITLE
unpatch mutating passed object

### ISSUE THREAD

**Issue by 0xorial** [benjamine/jsondiffpatch#138]
Hi! Very useful library! However, it is unclear from docs whether unpatch() should mutate passed parameter or not.

**Comment by benjamine** [comment]
unpatch does the opposite of patch, which also mutates the first parameter.

``` js
    // patch original
    jsondiffpatch.patch(country, delta);

    // reverse diff
    var reverseDelta = jsondiffpatch.reverse(delta);
    // also country2 can be return to original value with: jsondiffpatch.unpatch(country2, delta);
```

I'd think "patch original" and "country2 can be return to original value" are already implying that. the code example also shows below, the effect of patching `country`
