### ISSUE TITLE
Include version in bower.json

### ISSUE THREAD

**Issue by germanger** [benjamine/jsondiffpatch#139]
Is it possible to include "version" in "bower.json"?

My own application has several dependencies in my bower.json, eg:

    "dependencies": {
        "angular": "1.4.7",
        "angular-filter": "0.5.4",
        "angular-route": "1.4.7",
        "angular-sanitize": "1.4.7",
        "angular-cookies": "1.4.7",
        "angular-loading-bar": "0.7.1",
        "ng-grid": "~2.0.14",
        "angular-ui-select": "0.11.2",
        "AngularJS-Toaster": "0.4.15",
        "angular-bootstrap": "1.2.4",
        "bootstrap-css-only": "3.3.4",
        "angular-translate": "2.7.0",
        "angular-translate-storage-cookie": "2.7.0",
        "angular-chart.js": "0.7.1",
        "jsondiffpatch": "*",         /* No specific version */
        "agGrid": "2.3.5"
    }

All of them have a specific version... except for jsondiffpatch

So every time I run "bower install", I'm pretty sure everything is going to be OK with all of my dependencies (because I've tested all of those specific versions), except for jsondiffpatch...

**Comment by benjamine** [comment]
bower lets you use git tags to specify versions, and it seems to work fine for me:
`bower install --save jsondiffpatch#v0.1.41`
added
``` json
 "jsondiffpatch": "v0.1.41"
```
to bower.json

**Comment by germanger** [comment]
Ahhh! Perfect.
