### ISSUE TITLE
Strange move from index 1 to index 1

### ISSUE THREAD

**Issue by Yankovsky** [benjamine/jsondiffpatch#141]
`{"a":[1,2,3]}` | `{"a":[3,2,1]}` -> 
```
{
  "a": {
    "_t": "a",
    "_1": [
      "",
      1,
      3
    ],
    "_2": [
      "",
      0,
      3
    ]
  }
}
```

Is it correct and expected behavior?

**Comment by benjamine** [comment]
yes, I know that looks a little weird, but the key to understand it is `_1` means removed from index 1 in left array (that's what the underscore means), and `1` means inserted at index 1 in the right array (index 1 in left array !== index 1 in right array).

the process (of patching) that diffs represents is:
- remove `3` from index 2 (array is [1, 2])
- remove `2` from index 1 (array is [1])
- insert `3` at index 0 (array is [3, 1])
- insert `2` at index 1 (array is [3, 2, 1])

**Comment by Yankovsky** [comment]
Got it, found it in documentation [here](https://github.com/benjamine/jsondiffpatch/blob/master/docs/arrays.md)
Thank you!
