### ISSUE TITLE
Custom plugin for supporting default values for some keys

### ISSUE THREAD

**Issue by Yankovsky** [benjamine/jsondiffpatch#142]
Hi! I want to find diff between 2 objects considering default values for some keys. These default values should work as if properties are undefined.
Example:
a
```
{
  x: null
}
```
b
```
{
  x: 5
}
```
defaultValues:
```
{
  x: null
}
```
jsondiffpatch.diff(a, b)
current result:
```
{
  "x": [
    null,
    5
  ]
}
```
desired result:
```
{
  "x": [
    5
  ]
}
```

As I understand, I should write custom plugin to make it work. Could you give me some advice on where should I start?

Thank you for great library.

**Comment by Yankovsky** [comment]
I think I've got it:
```
function defaultValuesFilter(context) {
  var name = context.childName;
  var defaultValue = defaultValues[name];
  if (context.left === defaultValue ) {
    context.left = undefined;
  }
  if (context.right === defaultValue ) {
    context.right = undefined;
  }
}
defaultValuesFilter.filterName = 'defaultValues';
diffpatcher.processor.pipes.diff.before('trivial', defaultValuesFilter);
```
Is it safe to assign undefined?

**Comment by benjamine** [comment]
nice, I understand now that I see the plugin, that's perfect, looks good to me :+1:

**Comment by Yankovsky** [comment]
Thanks! It was so easy to extend, I can't believe it, that it was so easy to extend.

**Comment by Yankovsky** [comment]
Ok, now I have a bit more complex case. Same context as before, but now default value is object:
```
{
  x: {y: null}
}
```
a:
```
{
  x: {y: null}
}
```
b:
```
{
  x: {y: 5}
}
```
Same as before I want to treat `x: {y: null}` as `x: undefined`. But if I assign undefined to x in custom filter, then I am editing the source object. And if I use `cloneDiffValues: true` optio, then I get `Cannot read property '0' of undefined` error from:
```
DiffContext.prototype.setResult = function(result) {
  if (this.options.cloneDiffValues) {
    var clone = typeof this.options.cloneDiffValues === 'function' ?
      this.options.cloneDiffValues : function(value) {
        return JSON.parse(JSON.stringify(value), dateReviver);
      };
    if (typeof result[0] === 'object') {
      result[0] = clone(result[0]);
    }
    if (typeof result[1] === 'object') {
      result[1] = clone(result[1]);
    }
  }
  return Context.prototype.setResult.apply(this, arguments);
};
```

**Comment by Yankovsky** [comment]
Is it possible to add `if (result)` condition around 
```
if (typeof result[0] === 'object') {
      result[0] = clone(result[0]);
    }
    if (typeof result[1] === 'object') {
      result[1] = clone(result[1]);
    }
```
in DiffContext.prototype.setResult?

**Comment by benjamine** [comment]
I see, makes sense, that looks like a bug I introduced when adding `cloneDiffValues` option, not considering `undefined` result.

**Comment by Yankovsky** [comment]
Thank you!
