### ISSUE TITLE
Error: text diff_match_patch library not found at 60 character length?

### ISSUE THREAD

**Issue by shaunwarman** [benjamine/jsondiffpatch#143]
We seem to be running into a weird 60 character threshold and I noticed a hint in the [options section] (https://github.com/benjamine/jsondiffpatch#options)

```
textDiff: {
        // default 60, minimum string length (left and right sides) to use text diff algorythm: google-diff-match-patch
        minLength: 60
    },
```

Is this actually referring to a default of length 60? Strings less than 60 are fine. No issues.

Strings longer than 60 characters and we see:
`Error: text diff_match_patch library not`

Should I just update the options of `minLength`? Or is the documentation mean `maxLength`?

**Comment by shaunwarman** [comment]
Or sorry... better yet is there a recommended library for the `google-diff-match-patch` algorithm to add along with this?

**Comment by shaunwarman** [comment]
jsondiffpatch.full.js main bundle + google-diff-match-patch library for text diffs

Sorry found it!

**Comment by benjamine** [comment]
:+1:

**Comment by gokatz** [comment]
So we need to install this library manually in the host project?
