### ISSUE TITLE
Difference between live demo and npm package

### ISSUE THREAD

**Issue by 0xorial** [benjamine/jsondiffpatch#144]
Hi! I ran into a strange issue. I have an array of objects and tracking its changes. All objects have an 'id' field. The problem happens when I remove an item from an array. Here is a [jsFiddle ](http://jsfiddle.net/u99e2fhp/1/) demonstrating what happens. And the weirdest thing is that is different from what I get when pasting data to Live Demo. There I get what I expect - diff with one item removal.

**Comment by benjamine** [comment]
you need to specify an objectHash function that uses `id` field (live demo does).
https://github.com/benjamine/jsondiffpatch/blob/master/docs/arrays.md#an-example-using-objecthash

**Comment by 0xorial** [comment]
Thanks! Than works!
