### ISSUE TITLE
question on .full.js file

### ISSUE THREAD

**Issue by praveenakode** [benjamine/jsondiffpatch#149]
jsondiffpatch-full.min.js seems to point to non-minified version

**Comment by benjamine** [comment]
https://github.com/benjamine/jsondiffpatch/blob/master/public/build/jsondiffpatch-full.min.js
this file?

**Comment by praveenakode** [comment]
Yes.

**Comment by benjamine** [comment]
that file is minified. compare to https://github.com/benjamine/jsondiffpatch/blob/master/public/build/jsondiffpatch-full.js

**Comment by praveenakode** [comment]
my bad. looks fine. thanks
