### ISSUE TITLE
multiple json diff

### ISSUE THREAD

**Issue by kodeprav** [benjamine/jsondiffpatch#151]
Hi,
I am trying to diff multiple json files at a time and generate a diff file. I was able to generate diff file. 
If I have a diff  { "key": [1,1,0,0] }, I would like to highlight 1,1 with a certain color and 0,0 with a different color. Can I get some pointers on how to implement formatters for this?

**Comment by benjamine** [comment]
I'm not sure I understand, but the html formatter converts a diff to html, colored using css, you can then use any html manipulation technique, eg. use jQuery (browser-side) or Cheerio (server-side) to modify the html as needed.
