### ISSUE TITLE
Angular Version of the Demo?

### ISSUE THREAD

**Issue by maggieg123** [benjamine/jsondiffpatch#159]
While this is not an issue per se, I couldn't find anywhere to message/comment; I am interested in recreating the demo (specifically for the JSON diff) in AngularJS - has this been done/does an AngularJS version exist for the jsondiffpatch?

**Comment by benjamine** [comment]
there has been a discussion about using this in angular here https://github.com/benjamine/jsondiffpatch/issues/77

basically, I don't think using this it an angular app has any particular concern. as mentioned in that thread though if you're diffing angular scope objects, you might want to specify a `propertyFilter` to ignore angular internal properties (things that start with `$`), as shown in the example options at: https://github.com/benjamine/jsondiffpatch#options

**Comment by benjamine** [comment]
sorry, regarding messaging, I have email and twitter DM visible at my profile, thanks!

**Comment by maggieg123** [comment]
Thank you! I guess I was looking for a Plunkr or Fiddle with jsondiffpatch in AngularJs - unfortunately wasn't able to get it going yet, but it could just be PEBKAC.

**Comment by benjamine** [comment]
@maggieg123 np, it really depends on how you want to use it in an angular app, I don't have a demo but I might help if you get stuck with something.
