### ISSUE TITLE
use more than one keys as object id in objectHash()

### ISSUE THREAD

**Issue by androidkencai** [benjamine/jsondiffpatch#162]
let say
var objA = {"key1": 11, "key2": 12, "value": "value1"}
var objB = {"key1": 11, "key2": 22, "value": "value2"}
var objC = {"key1": 13, "key2": 12, "value": "value3"}

we combine key1 and key2 as the ID of the object, so the IDs of three objects are unique. can we use the objectHash() to specify combining key1 and key2 as the ID of object?

Thanks!
kc

**Comment by benjamine** [comment]
@androidkencai sure, as soon as the return value of objectHash() can be compared using `===`. there are a couple of options you could inside your objectHash() function to do that:
- simply concat them into a string or number (somehow)
- use an object hashing lib like https://github.com/puleos/object-hash (something like immutable.js might be an overkill but it works if you're into it)

**Comment by androidkencai** [comment]
@benjamine thanks for the suggestion. it works great!
