### ISSUE TITLE
Revert to original data

### ISSUE THREAD

**Issue by chendachao** [benjamine/jsondiffpatch#168]
I'm wondering if there is a method allow us to revert to original object,
Here I have `obj1`, and I changed it to `obj2`, and then `obj3`, and there are `delta1` and `delta2`, is ot possible for me to get `obj1` from `obj3` and `delta2`?

**Comment by benjamine** [comment]
if I understand correctly you also need `delta1`, and yes, there's an example of that in the README.
``` js
obj2 = jsondiffpatch.unpatch(obj3, delta2);
obj1 = jsondiffpatch.unpatch(obj2, delta1);
```
