### ISSUE TITLE
Problem with cyrillic

### ISSUE THREAD

**Issue by buryndin** [benjamine/jsondiffpatch#169]
When diff_match_patch library calculates diff for string with cyrillic symbols It encode result with [encodeURI](https://github.com/benjamine/jsondiffpatch/blob/master/public/external/diff_match_patch_uncompressed.js#L2148) function. So jsondiffpatch returns incorrect diffs. For example for strings
left: `Здесь ты всегда можешь посмотреть подсказки, чтобы играьт было еще веселее и интереснее!`
right: `Здесь ты всегда можешь посмотреть подсказки, чтобы играть было еще веселее и интереснее!`
it returns 
`[ '@@ -52,10 +52,10 @@\n %D0%B8%D0%B3%D1%80%D0%B0\n-%D1%8C\n %D1%82\n+%D1%8C\n  %D0%B1%D1%8B%D0%BB\n',
  0,
  2 ]`
instead of
`[ '@@ -52,10 +52,10 @@\n игра\n-ь\n т\n+ь\n  был\n', 0, 2 ]` 
It may be fixed by removing `encodeURI` from [this line](https://github.com/benjamine/jsondiffpatch/blob/master/public/external/diff_match_patch_uncompressed.js#L2148). But I'm not sure that's enough. But it certainly works!

**Comment by Pr1st0n** [comment]
Experiencing same issue.
I think [comment-71026452](https://github.com/benjamine/jsondiffpatch/issues/70#issuecomment-71026452) would be helpfull for you.

**Comment by buryndin** [comment]
Ok, but how can I solve problem with cyrillic?

**Comment by Pr1st0n** [comment]
Have not found a proper solution yet. But I think I'll try to fix this soon.

**Comment by benjamine** [comment]
unicode support into text diffs was fixed recently:

![image](https://user-images.githubusercontent.com/384553/38067669-fdd1cde4-32e3-11e8-813e-a83fed3a05dc.png)
