### ISSUE TITLE
Gulp injector not injecting needed files.

### ISSUE THREAD

**Issue by mattspaulding** [benjamine/jsondiffpatch#176]
The gulp injector is not recognizing some of the files that the application requires.

The `bower.json` only references this file
> "public/build/jsondiffpatch.js"

but all of these are needed

>  "public/build/jsondiffpatch.js",
>  "public/build/jsondiffpatch-formatters.js",
>  "public/formatters-styles/annotated.css",
>  "public/formatters-styles/html.css"

**Comment by mattspaulding** [comment]
#175 solves this.

**Comment by Methuselah96** [comment]
As noted [here](https://github.com/benjamine/jsondiffpatch/pull/175#issuecomment-364798855), this should no longer be necessary.
