### ISSUE TITLE
Can't seem to patch diff

### ISSUE THREAD

**Issue by alifhughes** [benjamine/jsondiffpatch#177]
Hey there,

I'm having trouble on my patching a diff on my server side code. I'm reusing/refactoring the differential synchronisation code from [this](https://github.com/janmonschke/Web-Audio-Editor) project and particularly looking at [this file.](https://github.com/janmonschke/Web-Audio-Editor/blob/master/server/synchronization.js) Within which, it is applying patches to diff of edits passed in from client side. However, I think realise I need an objectHash to do a 'non-dumb patch' but if I try to do it using his method: 

    // set up object comparison
    jsondiffpatch.config.objectHash = function(obj) { return obj.id || JSON.stringify(obj); };

I get the following error: 

    /Path/to/project/sync/sync.js:32
        jsondiffpatch.config.objectHash = function(obj) { return obj.id || JSON.stringify(obj); };
                                            ^

    TypeError: Cannot set property 'objectHash' of undefined

So I tried to implement it in the way that is seen in your examples: 

    // Set up object comparison                                                       
    jsondiffpatch = jsondiffpatch.create({
          objectHash: function(obj) {                                                   
                return obj.id || JSON.stringify(obj);                                     
          }
    });

But still it isn't patching at all. Do you have any idea as to what I could be doing wrong? It seems like it should work as I'm not doing anything too complex but still the patch just doesn't do anything.. 

An edit looks like this:

    { tracks: { _t: 'a', _0: [ [Object], 0, 0 ] } } 

To an object like this:

    { _id: '58d26cabd543b12c8bf6133e',
      bpm: 120,
      type: 'arrangement',
      name: 'sup',
      ownerId: '58c574df419e1116075b38f6',
      __v: 0,
      tracks: [],
      contributors: [] }

Thanks in advance, any help on the matter would be greatly appreciated.

**Comment by benjamine** [comment]
the 2nd form to config you show is correct (the other one might be an older version).
the example you show seems to be fine, but the patch says "delete first item of tracks array", and the object you're patching has an empty tracks array, so there's nothing to patch.

You can try this live, and have a readable description of what the delta means at:
http://benjamine.github.io/jsondiffpatch/demo/

**Comment by benjamine** [comment]
![image](https://cloud.githubusercontent.com/assets/384553/24226486/57bf4b1a-0f45-11e7-9e4e-f454df4ff959.png)

**Comment by alifhughes** [comment]
Thanks for you reply and sorry the delay in mine. You are correct which made me look to my code and the bug stemmed from putting the JSON objects to make the diff in the wrong order so it was always comparing them wrong. Sorry for this minor error on my behalf, your time and patience is very appreciated!
