### ISSUE TITLE
Documentation: Clarify relationship with RFC 6902

### ISSUE THREAD

**Issue by danvk** [benjamine/jsondiffpatch#183]
Is this an implementation of RFC 6902? A competing approach? A superset?

Would be great to get a quick sentence about this in the README.

**Comment by benjamine** [comment]
yes, that standard came up after the lib, and despite there's a formatter (with 2 bugs recently created btw), it created confussion about it's relation with this lib. I'm tagging it as help wanted to indicate a PR to add a note on this on the README.md would be welcomed.

**Comment by benjamine** [comment]
solved by #188
