### ISSUE TITLE
Weird output when comparing the diff of URLs in the JSON

### ISSUE THREAD

**Issue by contractorwolf** [benjamine/jsondiffpatch#184]
I have 2 urls (named applyNowLink in the JSON) that is the only difference in 2 JSON blocks. One has just "--TEST_TEST_TEST" added to the end of the URL. When I diff the two JSON blocks, this is what is output:
`{{
  "applyNowLink": [
    "@@ -193,19 +193,4 @@\n 3D01\n--TEST_TEST_TEST\n",
    0,
    2
  ]
}}`

when I change

**Comment by benjamine** [comment]
"Weird" is not a bug, what you're seeing is a GNU diff (the diff format used by all version control systems).

> includes google-diff-match-patch for long text diffs (diff at character level)

you can configure textDiff minLength using options: https://github.com/benjamine/jsondiffpatch#options
