### ISSUE TITLE
Count Diffs?

### ISSUE THREAD

**Issue by joshrathke** [benjamine/jsondiffpatch#187]
It's friday, so maybe I am just completely running on empty. But is there a good way to extract the number of "diff" between two objects?

**Comment by benjamine** [comment]
it might depend on what you count as a diff,
but I suspect thats something you'd do by processing the output delta

**Comment by benjamine** [comment]
count the number of arrays found in the delta object, recursively?

**Comment by joshrathke** [comment]
Yep, that's actually what I was thinking. Assuming every diff is represented by an array of the left hand operator and the right hand operator. Is that correct?

**Comment by benjamine** [comment]
correct, you can traverse the object and +1 everytime you find an array (and dont enter the array)

**Comment by joshrathke** [comment]
Awesome! I'll come up with something next week and make sure to post it back here. Might be a useful helper to include in the project?

**Comment by benjamine** [comment]
cool, thanks. it could be, I would avoid bundling it, but it could be a
plugin as formatters are (they live in a separate bundle)

**Comment by benjamine** [comment]
ok, I'll close this ticket, feel free to PR a new formatter (see formatters docs) if needed
