### ISSUE TITLE
Patch only missing items

### ISSUE THREAD

**Issue by janvv** [benjamine/jsondiffpatch#194]
Hi,

I'd like to know a way of only adding missing keys, while ignoring keys that are different.
This is useful for patching config json with new options keeping the current config intact.

**Comment by benjamine** [comment]
@janvv can you share a specific example? if what you want is to modify the behavior of jsondiffpatch.path, it's doable writing a jsondiffpatch plugin (see link in README), those can be used to intercept and override parts of the patch algorithm.

**Comment by janvv** [comment]
Suppose you have settings file like this:
{ "setting1": "default_value", "setting2": "default_value" }
Users can change those settings, so the file can be different for a particular user:
{ "setting1": "value_x", "setting2": "value_y" }
When I now introduce a new setting, then the new version of my app will have this settings file:
{ "setting1": "default_value", "setting2": "default_value", "setting3": "default_value" }
It would be nice to able to patch this for the existing user, keeping his customizations:
{ "setting1": "value_x", "setting2": "value_y", "setting3": "default_value" }

Not a very big deal, because in the meantime I am handling the default value in the source when a specific setting is not found in the config file.

**Comment by benjamine** [comment]
I see, so if I understand correctly, maybe this problem can be solved using [lodash merge](https://lodash.com/docs/4.17.4#merge), which performs a deep merge on objects (won't handle arrays properly).
``` js
const newSettings = _.merge({}, defaultSettings, existingUserSettings);
```
that way `newSettings` will preserve `existingUserSettings`, but adding anything missing from `defaultSettings`.

**Comment by benjamine** [comment]
(then if needed, you could use `jsondiffpatch` to find out what changed between them)

**Comment by janvv** [comment]
Super. Will have a look at it. Thx!
