### ISSUE TITLE
Coverage data is included in dist bundles

### ISSUE THREAD

**Issue by ian-craig** [benjamine/jsondiffpatch#212]
In version 0.3.5 code coverage data is included in `dist/jsondiffpatch.cjs.js` (and other dist files).

Two issues:
1. This file is 320K with coverage data, would be only 79K without
2. Because the coverage is already calculated it's very hard to ignore in projects which import this and have their own coverage checks.

In my case issue 2 is causing my build to fail because the coverage reporters pick up code coverage from path `Users/benja/proj/jsondiffpatch/src` which does not meet our more strict coverage requirements. I haven't found a way with our Jest config to exclude this so far. It excludes generating coverage for node_modules etc, but already generated coverage is harder to filter out. If anyone has ideas... ?

There are a few options I can think of to exclude coverage from the package:
* Builds with coverage, and tests, could be built into a separate `/build/` directory.
* Add a `dist/jsondiffpatch.esm.coverage.js` which `test/index.js` imports, and exclude coverage from other bundles.
* `npm run prepublish` could build with a slightly different environment to exclude coverage (e.g. https://github.com/rollup/rollup-starter-project/blob/master/rollup.config.js )

**Comment by benjamine** [comment]
oh yes coverage folder souldn't be included, 
in my local machine at least I see `/coverage` only in the root folder,
are you sure it's on npm? I can't see it there, see https://cdn.jsdelivr.net/npm/jsondiffpatch@0.3.5/dist/ for example

**Comment by ian-craig** [comment]
The `/coverage` directory is not included, but the data used to generate these reports is packaged into the `.js` files in `/dist` which are.

Here is what I see in `/node_modules/jsondiffpatch/`
![image](https://user-images.githubusercontent.com/2031632/36231855-76927c36-1194-11e8-9065-d3254c95dcac.png)

You can see this at https://cdn.jsdelivr.net/npm/jsondiffpatch@0.3.5/dist/jsondiffpatch.cjs.js by searching for "\_\_coverage\_\_".

I've confirmed that removing the istanbul plugin from the `// CommonJS (for Node) and ES module (for bundlers) build.` config in `rollup.config.js` fixes the issue, but that also prevents coverage showing in `npm run test` because `test/index.js` imports `dist/jsondiffpatch.cjs.js`.

**Comment by benjamine** [comment]
oh my bad, I see, silly mistake I'm instrumenting all the bundles, while I only need to instrument the "test", which I can exclude from npm.

**Comment by ian-craig** [comment]
I'm happy to submit a PR to resolve this, but there are a number of options. My preferred would be to create a `/build` folder which is used for everything except the `dist` build (which remains in `/dist`).

@benjamine before I go ahead does this sound OK to you?

**Comment by benjamine** [comment]
@ian-craig makes sense, it does looks a bit weird to include the test bundle with `dist`ributables.

my only problem is I include the test bundle in the npm package to allow a test on a browser, that's what this page uses:
https://benjamine.github.io/jsondiffpatch/test/index.html (pulls test bundle from npm using jsdelivr)
I would like to keep that page working, unless we find another way? ... I'd keep the test bundles there :(
