### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by DennisSmolek** [benjamine/jsondiffpatch#213]
Hey benjamine, totally love the code, we use it to handle history for an online editor. I see you're making some breaking changes (or at least using a 3.x version) but there isn't a changelog to see whats up and if I should change.

Would it be possible to add one or perhaps point me to where one exists?

**Comment by benjamine** [comment]
it's a good point, backward breaking changes have been very rare (or none?) so far, but would make sense to have one.
re. `0.3.x`, it has no API changes, the only difference is deprecated support for node < 4.8

**Comment by changelox** [comment]
Hi @benjamine, are you interested in maintaining a changelog? We are currently working on a service [changelox.com](changelox.com) to make changelog maintenance much easier without being a simple changelog generator. It's free for open source repos and we would appreciate your feedback. :)

**Comment by benjamine** [comment]
@changelox thanks, I would rather not add a dependency, and rely on a simple text file.

**Comment by Methuselah96** [comment]
Changes are now document from 0.4.0 on in [Releases](https://github.com/benjamine/jsondiffpatch/releases).
