### ISSUE TITLE
No more css files

### ISSUE THREAD

**Issue by plugged** [benjamine/jsondiffpatch#218]
After updating to 0.3.x there are no css files in node_modules/jsondiffpatch

In 0.2.x I used css from @import "~jsondiffpatch/public/formatters-styles/html.css";

**Comment by benjamine** [comment]
nice catch 👍 , fixed on v0.3.8

I included `/dist/formatter-styles/html.css` and `/dist/formatter-styles/annotated.css` on the npm package, as can be seen here: https://cdn.jsdelivr.net/npm/jsondiffpatch@0.3.8/dist/formatters-styles/
