### ISSUE TITLE
Angular 4:  TypeError: Cannot read property 'html' of undefined

### ISSUE THREAD

**Issue by hanijazzar** [benjamine/jsondiffpatch#219]
Using Angular 4 and trying to use formatters. Getting the error " TypeError: Cannot read property 'html' of undefined" in the console when using:
`let delta2 = diffPatcher.formatters.html.format(delta, orig);`

Seems formatters is undefined. Any idea how to solve this issue?

**Comment by benjamine** [comment]
`jsondiffpatch.formatters` is a property on the top-level module (ie. you can access it literally like that), but it's not a property of a diffpatcher instance (I assume that's an instance you created using `jsondiffpatch.create(...)`)

**Comment by hanijazzar** [comment]
Thank you for your reply.
In the imports I have:

         `import { DiffPatcher } from 'jsondiffpatch/public/build/jsondiffpatch';`

and then in my function I have:

       `let diffPatcher = new DiffPatcher();
        let delta = diffPatcher.diff(cF, cA);
        let delta2 = diffPatcher.formatters.html.format(delta, cF);`

**Comment by hanijazzar** [comment]
Now
