### ISSUE TITLE
jsonpatch formatter array move generates incorrect patch

### ISSUE THREAD

**Issue by slubowsky** [benjamine/jsondiffpatch#230]
When I submit a jsonpatch including a move to my ASP.NET core backend, it throws an exception:
`Microsoft.AspNetCore.JsonPatch.Exceptions.JsonPatchException: 'The target location specified by path segment '0' was not found.'`
The generated patch looks like this:
`[{"op":"move","from":"/myArray/1","path":"/0"}]`
If I fix it to look like this:
`[{"op":"move","from":"/myArray/1","path":"/myArray/0"}]`
Then it no longer throws an exception (though it still doesn't work correctly for me in my case, but that appears to be a separate ASP.NET issue).

Looking at the spec [https://tools.ietf.org/html/rfc6902#section-4.4](https://tools.ietf.org/html/rfc6902#section-4.4) it appears that ASP.NET is correct to expect the full path for the to location just as is given for all other array operations.

**Comment by benjamine** [comment]
@slubowsky can you submit a full example of the issue? ie. the full json of these:
- left value
- right value
- the generated delta
- jsonpath

**Comment by slubowsky** [comment]
Not sure which value you want for "jsonpath" but hopefully included everything you need in this example

left:
```
{
  "id": 1,
  "middleName": "z",
  "referenceNumbers": [
    {
      "id": 3,
      "payorId": 19,
      "referenceNumber": "123",
      "startDate": "1980-01-01T05:00:00.000Z",
      "endDate": null,
      "index": 0
    },
    {
      "id": 1,
      "payorId": 55,
      "referenceNumber": "456",
      "startDate": "1980-01-01T05:00:00.000Z",
      "endDate": null,
      "index": 1
    },
    {
      "id": 2,
      "payorId": 56,
      "referenceNumber": "789",
      "startDate": "1980-01-01T05:00:00.000Z",
      "endDate": null,
      "index": 2
    }
  ]
}
```

right:
```
{
  "id": 1,
  "middleName": "x",
  "referenceNumbers": [
    {
      "id": 1,
      "payorId": 55,
      "referenceNumber": "456",
      "startDate": "1980-01-01T05:00:00.000Z",
      "endDate": null,
      "index": 0
    },
    {
      "id": 3,
      "payorId": 19,
      "referenceNumber": "123",
      "startDate": "1980-01-01T05:00:00.000Z",
      "endDate": null,
      "index": 1
    },
    {
      "id": 2,
      "payorId": 56,
      "referenceNumber": "789",
      "startDate": "1980-01-01T05:00:00.000Z",
      "endDate": null,
      "index": 2
    }
  ]
}
```

diff:
```
{
  "middleName": [
    "z",
    "x"
  ],
  "referenceNumbers": {
    "0": {
      "index": [
        1,
        0
      ]
    },
    "1": {
      "index": [
        0,
        1
      ]
    },
    "_t": "a",
    "_1": [
      "",
      0,
      3
    ]
  }
}
```

patch:
```
[
  {
    "op": "replace",
    "path": "\/middleName",
    "value": "x"
  },
  {
    "op": "replace",
    "path": "\/referenceNumbers\/0\/index",
    "value": 0
  },
  {
    "op": "move",
    "from": "\/referenceNumbers\/1",
    "path": "\/0"
  },
  {
    "op": "replace",
    "path": "\/referenceNumbers\/1\/index",
    "value": 1
  }
]

```

**Comment by benjamine** [comment]
thanks! (I meant that last json you included, that's a jsonpath document).

this should do 👍 , would you mind maybe write what would be the expected value for this last json? what would you expect to obtain?
I can turn that into a failing test and go from there.

**Comment by slubowsky** [comment]
Thank you.
expected value for jsonpath below (move path is complete, not just index)
```
[
  {
    "op": "replace",
    "path": "\/middleName",
    "value": "x"
  },
  {
    "op": "replace",
    "path": "\/referenceNumbers\/0\/index",
    "value": 0
  },
  {
    "op": "move",
    "from": "\/referenceNumbers\/1",
    "path": "\/referenceNumbers\/0"
  },
  {
    "op": "replace",
    "path": "\/referenceNumbers\/1\/index",
    "value": 1
  }
]
```

**Comment by benjamine** [comment]
sweet thanks! will try to look at this today/tomorrow

**Comment by slubowsky** [comment]
@benjamine Seems theres another issue here as well. According to the spec [https://tools.ietf.org/html/rfc6902#section-3](https://tools.ietf.org/html/rfc6902#section-3) operations are to be performed in order
This means that the patch documented above is incorrect in another way as well. The second replace operation comes after the move and as such the index used should be the new index of 0 as the move would have already been applied and the index would now be 0.
```
{
    "op": "replace",
    "path": "\/referenceNumbers\/0\/index",
    "value": 1
 }
```
Perhaps rather then fixing the index it might be simpler to order the patch such that all moves come after all replace operations. This way the replace operations can use the original indexes before any moves change things. 

(Haven't checked but add and remove might have similar issue. If replace is after an add or a remove the index in the patch must be the new index - and what if you have multiple moves, adds, removes etc.. Is the index for each correct based on the current state assuming the previous one was applied? ouch...)

**Comment by aryelu** [comment]
I'll look into it

**Comment by aryelu** [comment]
@slubowsky @benjamine here's a fix. plz confirm

**Comment by slubowsky-course** [comment]
@benjamine @aryelu Works as expected for my simple use case. I have not tested more sophisticated use cases though. Thanks!

**Comment by slubowsky** [comment]
@benjamine @aryelu Works as expected for my simple use case. I have not tested more sophisticated use cases though. Thanks!
