### ISSUE TITLE
Typings do not include showUnchanged and hideUnchanged for html formatter

### ISSUE THREAD

**Issue by ian-craig** [benjamine/jsondiffpatch#234]
Typings (`index.d.ts`) for the html formatter only include the `format` method. 

```ts
export interface Formatter {
  format(delta: Delta, original: any): string;
}

export const formatters: {
  annotated: Formatter;
  console: Formatter;
  html: Formatter;
};
```

`showUnchanged` and `hideUnchanged` should also be present.

Given these are only on the HTML formatter we'll probably need to add a separate type for this.

**Comment by benjamine** [comment]
thanks 👍 , I'm not familiar with the TS annotation myself, I could give it a try but a PR would be very welcome for this.

**Comment by ian-craig** [comment]
@benjamine Any update on when this will be merged and a new version published? I'd love to be able to remove the workarounds in my projects for this and another open PR.
