### ISSUE TITLE
jsondiffpatch.dateReviver not present in typescript types

### ISSUE THREAD

**Issue by jakubzloczewski** [benjamine/jsondiffpatch#235]
Hi, I'm using Typescript in my project and after installation (yarn install jsondiffpatch) I found that index.d.ts is present but dateReviver type is not present.

My workaround is to use this notation: `jsondiffpatch['dateReviver']`

**Comment by Methuselah96** [comment]
Fixed in https://github.com/benjamine/jsondiffpatch/pull/345.
