### ISSUE TITLE
Object doesn't support this action  in   the  jsondiffpatch.umd.js file

### ISSUE THREAD

**Issue by jakkirhussain** [benjamine/jsondiffpatch#243]
I am getting this error in IE8 compatible mode 

Object doesn't support this action  in   the  jsondiffpatch.umd.js file

error throws near this line 
Object.defineProperty(target,descriptor.key,descriptor)}}

**Comment by Methuselah96** [comment]
Hello, sorry for the delayed response!

I hope/expect that you no longer to support IE8 anymore, so I'm going to go ahead and close this, let me know if there's anything I can help with.
