### ISSUE TITLE
Chalk dependency causes issue with typescript in the browser

### ISSUE THREAD

**Issue by sebastiansandqvist** [benjamine/jsondiffpatch#249]
When using this project with Typescript, it imports the .esm file which has a dependency on `chalk`. Down the line, `chalk`, which isn't currently built to work in browsers, depends on `supports-color` which depends on `os` from the node standard library.

What is the recommended setup for using this project within a browser given that one of its dependencies isn't built for browser usage?

(This might not be a typescript-specific issue, it is just the environment in which I discovered this issue.)

**Comment by juliankrispel** [comment]
I'm also getting this, no matter what js compiler you're using:

![image](https://user-images.githubusercontent.com/1188186/45236480-dbc89780-b2d3-11e8-8dde-50fa34788372.png)

**Comment by leblancmeneses** [comment]
Changing my import fixed it for me.  

```
import {patch as jsonPatch, diff as jsonDiff} from 'jsondiffpatch';
```

**Comment by Methuselah96** [comment]
Hello, sorry for the delayed response!

I'm not able to reproduce this issue, can you specify what bundler/environment this is happening in?

**Comment by Methuselah96** [comment]
I'm going to go ahead and close this for now, let me know if this is still an issue for you.
