### ISSUE TITLE
Typescript: how to get an hold on BaseFormatter

### ISSUE THREAD

**Issue by FritzHerbers** [benjamine/jsondiffpatch#255]
I am trying to get an hold on BaseFormatter, but only something like base is exported (jsondiffpatch.esm.js).

[https://stackblitz.com/edit/typescript-sgf4s2](https://stackblitz.com/edit/typescript-sgf4s2)

How do I get BaseFormatter imported and get rid of any Typescript errors? Thanks for your help.

Also noticed:
In d.ts the provided jsonpatch formatter is missing.

**Comment by kareljuricka** [comment]
I just figured it out:
```
import { formatters } from 'jsondiffpatch';

export class CeosPropertyDiffFormatter extends (formatters as any).base.default {
}
```

**Comment by Methuselah96** [comment]
As of v0.6.0, you should now able to import the base formatter like so:

```ts
import BaseFormatter from 'jsondiffpatch/formatters/base';
import type { BaseFormatterContext } from 'jsondiffpatch/formatters/base';

export class CeosPropertyDiffFormatter extends BaseFormatter<BaseFormatterContext> {
  // impl
}
```

Let us know if you have any further issues.
