### ISSUE TITLE
Consider removing typing from repo in favour of DefinitelyTyped

### ISSUE THREAD

**Issue by mattdarveniza** [benjamine/jsondiffpatch#273]
The current `index.d.ts` is very incomplete and there are many PRs open and unaddressed with improved typing.

Rather than have these PRs languish in this repository, could we remove the index.d.ts all-together if the maintainers aren't able to keep these up to date, and keep the types in DefinitelyTyped instead?

I'd be happy to move the existing types plus those in PRs over, and update the README to point to these types that will be better maintained.

**Comment by tnrich** [comment]
That would be awesome @mattdarveniza 

Is there a way we could go ahead with the first part of this without needing approval from @benjamine ?

**Comment by Tagman** [comment]
That would make the library even more usefull in modern projects

**Comment by mattdarveniza** [comment]
Personally I don't want to port these over without permission from the author, partly out of respect and partly because I don't want to spend the time if they will be ignored over the existing types anyway. I'm not sure how type resolution works when there's an in-repo index.d.ts and a DefinitelyTyped entry at the same time.

If someone else wanted to have a go I wouldn't be mad though 😅
