### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by tnrich** [benjamine/jsondiffpatch#274]
Looks like there hasn't been any PR merged in quite a while.. ?

@benjamine what's your status?

**Comment by sjoerd222888** [comment]
No comment until now. @benjamine would be good to have a statement from you.

**Comment by benjamine** [comment]
I'm not currently adding new features, but yes will review any fixes sent.
I haven't had a lot of time o review PRs recently, but anything that is a fix (and includes tests verifying there's no breaking changes) let me know and I would incorporate.

**Comment by Offirmo** [comment]
@benjamine is there a changelog? It's fine if you don't have time, I understand.
Thanks for this great, invaluable module.

**Comment by benjamine** [comment]
Hi @Offirmo thank you!, I don't have a changelog, but should.
I think I'd love to have something (PRs accepted) somewhat automatic based on the commit message convention in https://commitlint.js.org (I've seen other libraries use github bots to keep that up to date)

**Comment by tnrich** [comment]
@benjamine I would recommend recruiting an additional trusted maintainer or two. It's been 2 years since the last commit and even longer since an actual meaningful commit was made. 

I just ran into an issue where the version being used by the jsondiffpatch dependency `chalk` is causing a build issue with newer build tools (like vite) - https://github.com/benjamine/jsondiffpatch/issues/315 

Now I'm using https://www.npmjs.com/package/jsondiffpatch-rc which doesn't feel great. 

It would be great if at the bare minimum the dependencies for this repo could be updated. 

Thanks! 

PS I would be happy to take on a maintainer role for this repo as we are still using it in our tools

**Comment by benjamine** [comment]
hi folks, apologies for the lack of replies.

I agree at least some help keeping dependencies up to date and any patches
would be great!

I’d love peering with a volunteer on this.

**Comment by Methuselah96** [comment]
Hey @benjamine, I'm the maintainer of redux-devtools which depends on this project and I would be interested in helping maintain this package if the offer still stands. Thanks!

**Comment by benjamine** [comment]
@Methuselah96 that'd be awesome! of course, will get in touch to get it done 💪 , thank you!

**Comment by Methuselah96** [comment]
Just released [v0.5.0](https://github.com/benjamine/jsondiffpatch/releases/tag/v0.5.0) which should fix Vite usage. Changes will be documented in [Releases](https://github.com/benjamine/jsondiffpatch/releases).

Hopefully with two maintainers we should be able to keep up maintenance.
