### ISSUE TITLE
what changed from 0.3.11 to 0.4.1 ? Is there a changelog?

### ISSUE THREAD

**Issue by mreinstein** [benjamine/jsondiffpatch#280]
I'm currently using jsondiffpatch@0.3.11 and I noticed we're now at 0.4.1. Given this hasn't hit 1.0.0 yet, are there any breaking changes I need to know about in doing an upgrade?

Thanks for a great module by the way!

**Comment by benjamine** [comment]
thanks @mreinstein !, the only breaking change is dropping support for legacy node.js versions (current minimum is v8),

ps: I'm considering adding some for of changelog, just looking into automatic mechanisms, but prob. should start with a simple manually written one first, will update here when I do, thanks!

**Comment by avindra** [comment]
There's no tag either. If anyone is looking for a quick summary, you can use this link

https://github.com/benjamine/jsondiffpatch/compare/v0.3.11...12f49b3306a7dabf3e223200d3db5f5716ecb4d9

**Comment by Methuselah96** [comment]
Changes are now document from 0.4.0 onward in [Releases](https://github.com/benjamine/jsondiffpatch/releases). Also added tags for the 0.4.x releases.
