### ISSUE TITLE
Missing /dist

### ISSUE THREAD

**Issue by BHare1985** [benjamine/jsondiffpatch#288]
readme says to look at /dist for UMD but there is no folder

**Comment by kshay** [comment]
We just ran into this too when trying to update to the latest release (apparently 0.3.11, though the code is up to 0.4.1). The old 0.1.x version we were using included a `public` directory with built files.

**Comment by 1j01** [comment]
Workaround: can download from https://unpkg.com/browse/jsondiffpatch@latest/dist/

**Comment by Methuselah96** [comment]
Hello, sorry for the delayed response!

The `dist` folder only exists when the library is built. The common way to access this is by installing the npm or by using a CDN service that serves npm packages.

Hopefully that helps, let me know if that answers your question.

**Comment by Methuselah96** [comment]
I'm going to go ahead and close this for now, let me know if this is still an issue for you.
