### ISSUE TITLE
cdnjs old version

### ISSUE THREAD

**Issue by BHare1985** [benjamine/jsondiffpatch#289]
https://cdnjs.com/libraries/jsondiffpatch

Not sure how this website keeps up to date, but could it get the new version? I exclusively use cdnjs as my js library cdn

**Comment by Methuselah96** [comment]
Hello, sorry for the delayed response!

I think it has the latest version, are you still having issues with this?

**Comment by Methuselah96** [comment]
I'm going to go ahead and close this for now, let me know if this is still an issue for you.
