### ISSUE TITLE
TS2339: Property 'log' does not exist on type 'Formatter'.

### ISSUE THREAD

**Issue by muescha** [benjamine/jsondiffpatch#292]
### docs

docs wrong for TypeScript at:

https://github.com/benjamine/jsondiffpatch/blob/master/docs/formatters.md#console

### where:

```javascript
jsondiffpatch.console.log(result)
```

### error:

```javascript
TS2339: Property 'log' does not exist on type 'Formatter'.
```

### workaround

```javascript
jsondiffpatch.formatters.console.format(result, null)
```
see also:
- #293 `TS2554: Expected 2 arguments, but got 1 at jsondiffpatch.formatters.console.format`

**Comment by Methuselah96** [comment]
Fixed in https://github.com/benjamine/jsondiffpatch/pull/345.
