### ISSUE TITLE
TS2554: Expected 2 arguments, but got 1  at jsondiffpatch.formatters.console.format

### ISSUE THREAD

**Issue by muescha** [benjamine/jsondiffpatch#293]
### docs

docs wrong for TypeScript at:

https://github.com/benjamine/jsondiffpatch/blob/master/docs/formatters.md#console

### where:

```javascript
jsondiffpatch.formatters.console.format(result)
```

### error

```javascript
TS2554: Expected 2 arguments, but got 1
```

### workaround

```javascript
jsondiffpatch.formatters.console.format(result, null)
```

**Comment by Aleeexx** [comment]
The readme says: `jsondiffpatch.formatters.html.format(delta, left);` (cmp. https://www.npmjs.com/package/jsondiffpatch#visual-diff)
