### ISSUE TITLE
Live Demo returns 404

### ISSUE THREAD

**Issue by lgarczyn** [benjamine/jsondiffpatch#306]
Every link to the live demo (https://benjamine.github.com/jsondiffpatch/demo/index.html) on the readme is broken

**Comment by sinedie** [comment]
it is fixed: (https://benjamine.github.io/jsondiffpatch/demo/index.html) Note the .io

**Comment by Methuselah96** [comment]
Should be fixed by https://github.com/benjamine/jsondiffpatch/pull/307, https://github.com/benjamine/jsondiffpatch/pull/311, and https://github.com/benjamine/jsondiffpatch/pull/317. Let us know there if there are any others that we missed.
