### ISSUE TITLE
Looks like there's no maintenance. I feel like it's hard to use. I want his view section, but it doesn't work

### ISSUE THREAD

**Issue by Deja-vuuu** [benjamine/jsondiffpatch#319]

**Comment by Methuselah96** [comment]
Hello, sorry for the delayed response!

This package is now being maintained again. You mention that the "view section" is not working, can you provide some details of what's not working about it or how to reproduce the issue you're experiencing?

**Comment by Methuselah96** [comment]
I'm going to go ahead and close this for now, let me know if this is still an issue for you.
