### ISSUE TITLE
URIError: malformed URI

### ISSUE THREAD

**Issue by AlabasterAxe** [benjamine/jsondiffpatch#325]
I'm still trying to work through what diff generated this but I figured I'd file this and can add more information as I discover it.

It looks like when diffing long strings with json diff patch, googles diff match patch utility can throw this malformed URI error.

**Comment by JulesLecuir** [comment]
I do have the same problem with identical strings, also containing emojis. Will investigate asap.

**Comment by AlabasterAxe** [comment]
Are you sure they're identical? This error can happen if the emoji only differ by a single surrogate unicode character.

**Comment by AlabasterAxe** [comment]
For example these two emoji differ by only a single character: 👈 (0xD83D, 0xDC49) and 👌 (0xD83D, 0xDC4C)). So if you diff long strings containing them the diff will contain a single emoji byte which will cause uri encode to fail.
