### ISSUE TITLE
Patch behavior when dealing with references

### ISSUE THREAD

**Issue by janmonschke** [benjamine/jsondiffpatch#34]
This is more a discussion than a bug or a feature request.

In my code I'm constantly diffing and patching two objects and I noticed the following behavior:
```javascript
var obj1 = {};
var obj2 = { arr: [{a:1}]};

var diff1 = jsondiffpatch.diff(obj1, obj2);
console.log('first diff:', diff1);

// patch the first object
jsondiffpatch.patch(obj1, diff1);

// change the object inside the array on object 2
obj2.arr[0].a = 2;

var diff2 = jsondiffpatch.diff(obj1, obj2);
console.log(diff2) // -> undefined
```
Run on JSFiddle: http://jsfiddle.net/janmonschke/F3qqL/

I was expecting the second diff to contain the change of the firs element in the array, but I got an empty diff. I guess it's because the patch method copies over references instead  of (a copy of) the object.

Is this behavior intended?

Since I'm only dealing with very small diffs in my application I simply create a deep copy of the diff before I patch the object. Which could be a general solution to the problem but I'm not sure how well that performs when applications are dealing with larger diffs.

**Comment by egeozcan** [comment]
JSON.stringify-ing the diff and parsing it again, of course, is a quick and dirty work-around to this issue.

**Comment by episodeyang** [comment]
lol I just run into exactly the same issue!

**Comment by benjamine** [comment]
ok, this should be solved with the new `cloneDiffValues` option.
if defaults to false, if `true`, values in the delta will be clones, preventing this issue (diff+patch+diff).

default `clone(value)` function is the simplistic JSON stringify+parse, you can specify one by using your function as value for this option (instead of just `true`).
https://github.com/benjamine/jsondiffpatch#options

**Comment by kflorence** [comment]
I still seem to have this issue on the latest version (`0.6.0`). I am saving deltas in an array. On entry, they are correct, but after executing `jsonDiffPatch.patch(obj, delta)` on the second delta, the previous delta is mutated. I have tried using `cloneDiffValues: true` as well as defining a custom one:

```javascript
  cloneDiffValues: function(value) {
    return JSON.parse(JSON.stringify(value))
  }
```

But this has no effect. It seems `cloneDiffValues` is not used for the method above. However, if I change the execution to `jsonDiffPatch.patch(obj, JSON.parse(JSON.stringify(delta)))` the previous delta is not mutated and everything works as expected.

Here you can see the deltas as they are generated.

First:
```json
{"layout":{"tiles":{"0":{"1":{"items":[[{"type":"Reflector"}]]},"_t":"a"},"1":{"0":{"items":[[{"type":"Reflector"}],0,0]},"_t":"a"},"_t":"a"}}}
```

Second:
```json
{"layout":{"tiles":{"0":{"0":{"items":{"0":{"color":["blue",0,0],"openings":[[null,null,null,{"type":"Beam"},null,null],0,0],"type":["Terminus","Reflector"]},"_t":"a"}},"1":{"items":{"0":{"type":["Reflector","Terminus"],"color":["blue"],"openings":[[null,null,null,{"type":"Beam"},null,null]]},"_t":"a"}},"_t":"a"},"_t":"a"}}}
```

After applying the second delta above, the first is modified to:
```json
{"layout":{"tiles":{"0":{"1":{"items":[[{"type":"Terminus","color":"blue","openings":[null,null,null,{"type":"Beam"},null,null]}]]},"_t":"a"},"1":{"0":{"items":[[{"type":"Reflector"}],0,0]},"_t":"a"},"_t":"a"}}}
```

As a workaround, I can just store the deltas in string format and `JSON.parse` them when I need them, but this is a very confusing bug that seems like it should already be fixed.
