### ISSUE TITLE
Missing types in the latest build

### ISSUE THREAD

**Issue by akharkhonov** [benjamine/jsondiffpatch#348]
It looks like the latest published build on npm is missing types that are present in the github repo
For example, the main.ts file has a smarter typing for Delta https://github.com/benjamine/jsondiffpatch/blob/master/src/types.ts#L36
but from the package itself, I can import only outdated Delta type
<img width="517" alt="image" src="https://github.com/benjamine/jsondiffpatch/assets/47464417/1537613c-6f1d-4f53-aa47-559bb2ef779f">

package version:  0.5.0

**Comment by Methuselah96** [comment]
This project was recently converted to TypeScript in https://github.com/benjamine/jsondiffpatch/pull/345. We are working on getting the new types released, but don't have an estimate of when that would be at this moment.

**Comment by akharkhonov** [comment]
@Methuselah96 got it, thanks for the reply, I just wanted to double-check if this is a known issue, but if it's expected then no problem, I'll just wait for the next release
