### ISSUE TITLE
Types for `jsonpatch` formatter

### ISSUE THREAD

**Issue by maslennikov** [benjamine/jsondiffpatch#349]
Hi! I have noticed that `formatters` types do not export `jsonpatch` field. Was it intentionally hidden?

I am trying to use it like this:
```ts
import jdp from 'jsondiffpatch'
jdp.formatters.jsonpatch.format(changes)
```

Typescript gives me:
```
Property 'jsonpatch' does not exist on type '{ annotated: Formatter; console: Formatter; html: HtmlFormatter; }'
```

Using version `"jsondiffpatch": "^0.5.0"`

**Comment by Methuselah96** [comment]
No, it's not intentionally hidden. We've recently converted the entire codebase to TypeScript which will fix this issue. We hope to get those changes released soon, but there's no estimate of when that will be.
