### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Jojoshua** [benjamine/jsondiffpatch#354]
The live demo in the readme and on google results for formatting output doesn't work

http://benjamine.github.io/jsondiffpatch/demo/index.html

**Comment by Methuselah96** [comment]
Thanks, I'll take a look at getting that fixed.

**Comment by PedroS5499** [comment]
Still not working

**Comment by Jays769** [comment]
Still not working

**Comment by Methuselah96** [comment]
Should be fixed now, let me know if you run into any more issues.
