### ISSUE TITLE
Support RegExp objects

### ISSUE THREAD

**Issue by jmeas** [benjamine/jsondiffpatch#36]
The `JSON.stringify` method treats RegExp objects as `{}`, leading to results like below:

```js
jsondiffpatch.diff( {}, /regex/ ); // => undefined
jsondiffpatch.diff( /someRegex/, /someOtherRegex/ ); // => undefined
```

I understand that RegExp objects don't serialize to JSON, but I'm wondering if, in some contexts, it would make sense for it to return (in the first example):

```js
[ '{}', /regex/ ] 
```

This would involve a bit more processing for RegExp objects beyond JSON.stringify, but I'm willing to write up a PR if you think that it's worth merging.

**Comment by benjamine** [comment]
ok, RegExp is now supported natively since 0.2.2 :),
(regexp is serialized with .toString and interpreted as such when patched value is a RegExp too, this won't solve json stringification of RegExp of course, for that you can do: `RegExp.prototype.toJSON = RegExp.prototype.toString`)
