### ISSUE TITLE
Packages on CDN are not working?

### ISSUE THREAD

**Issue by nguyenlamlll** [benjamine/jsondiffpatch#360]
Hi everyone, I'm following the section [Visual Diff](https://github.com/benjamine/jsondiffpatch?tab=readme-ov-file#visual-diff). I've created a standalone HTML file with the same codes. When I try to run, it does not render anything and it shows this error in the console log

```
build:jsondiffpatch@v0.6.0-3ZucslcM2zwGnqULgbGl:16 [Package Error] "jsondiffpatch@v0.6.0" could not be built. 
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
Cannot find module 'jsondiffpatch/formatters/styles/annotated.css'
```

It seems that something is wrong on the CDN? If you visit the cdn links directly, you'll see the same errors as well (e.g., this [link](https://cdn.skypack.dev/jsondiffpatch/formatters/styles/html.css))

**Comment by Methuselah96** [comment]
Thanks for raising the issue, I'm not sure what's going on there. As a workaround, you should be able to import it from esm.sh using the full file patch (i.e. `https://esm.sh/jsondiffpatch@0.6.0/lib/formatters/styles/html.css`). I'll try to dig into why importing it from `jsondiffpatch/formatters/styles/html.css` isn't working.
