### ISSUE TITLE
[Perf] Experiencing slow diffs on large arrays

### ISSUE THREAD

**Issue by soumilbaldota** [benjamine/jsondiffpatch#365]
Running it on chrome browser in the frontend
Chrome version : Latest
Ram: 16 GB
Processor: Ryzen 5 5000

I am trying to diff two string arrays.
These arrays are 20k in length.
It is taking ~5s to find the diff

Are there any options that I can modify to make the diff quicker?

Please find the minimal reproducible sample here:
https://github.com/soumilbaldota/jsondiffpatch-reprod

**Comment by samirotiv** [comment]
Posting here for users who need to solve this:

I made a small change - I ran the example in a loop for 10 iterations to bring out the problem more. I then inspected it using the flamegraph profiler in Chrome.

![image](https://github.com/benjamine/jsondiffpatch/assets/4405935/58ad556b-3093-41e3-9f0e-c13c168e7728)

This is what the left-heavy view of speedscope showed. There is one function called arraysHaveMatchByRef which is extremely expensive.
 
Going into the implementation of this function, it seems like an extremely expensive `O(n^2)` function only to check whether arrays have atleast one matching element which has changed index.

![image](https://github.com/benjamine/jsondiffpatch/assets/4405935/a479e031-f11c-476a-990b-567c719008a5)

Looking further, this is called by one place called DiffFilter which decides whether to perform a
_match by position_.

![image](https://github.com/benjamine/jsondiffpatch/assets/4405935/1886bac7-c8d6-4983-84da-bcc5da2804f5)

Refer to this link for more info on matching on position -
https://github.com/benjamine/jsondiffpatch/blob/master/docs/arrays.md

To get rid of this, there are two ways:
- Provide a trivial objectHash function which returns the object itself
  ![image](https://github.com/benjamine/jsondiffpatch/assets/4405935/3147dec4-e896-4fe5-b631-98e02214ad26)

- Provide a boolean called `matchByPosition = false` in the options
  ![image](https://github.com/benjamine/jsondiffpatch/assets/4405935/61d707fd-20a9-4187-9023-ae7f37b19a2b)

To perform the diff:
`result = differ.diff(idArr, updatedData);`
 
For some reason, the `matchByPosition` option is not documented anywhere in their README.md - if they document this, it will help users avoid this `O(n^2)` trap.

- Before optimization
  ![image](https://github.com/benjamine/jsondiffpatch/assets/4405935/549bb5b0-4af3-46e8-9d48-30b6dcb60c30)
- After optimization
  ![image](https://github.com/benjamine/jsondiffpatch/assets/4405935/c642caf4-03f2-4b15-8f32-81dd120f794d)

**Comment by samirotiv** [comment]
Looks like this was added to fix #157

**Comment by samirotiv** [comment]
@benjamine I would suggest as an improvement for a better out-of-the-box experience, we can enable `matchByPosition` if any of the two arrays contain atleast one non-primitive type (i.e. object). If all elements of the two arrays are strings, numbers, booleans or nulls, then `matchByPosition` can be `false`. This can be checked in `O(n)` time.
