### ISSUE TITLE
 Node.js Version Restriction in 'engines' Configuration

### ISSUE THREAD

**Issue by katoto** [benjamine/jsondiffpatch#375]
"Hello,
I noticed that your project specifies the 'engines' configuration as follows:

```
"engines": {
  "node": "^18.0.0 || >=20.0.0"
}
```
Could you please explain why you've chosen to restrict the Node.js versions to these specific ranges? Is there a particular reason for not including versions 19.x? Understanding the rationale behind this decision would be helpful for users who might be working with Node.js 19.x.

Thank you for your time and for maintaining this project."

**Comment by Methuselah96** [comment]
Those were just the supported Node.js releases at the time of the last release. Node.js 18 is LTS and [still supported](https://nodejs.org/en/about/previous-releases), but Node.js 19 is not.
