### ISSUE TITLE
Why is encodeURI used in patch_obj.toString?

### ISSUE THREAD

**Issue by TomDmitriev** [benjamine/jsondiffpatch#70]
Is there a reason for that? The issue I'm facing is that it converts Cyrillic text to some undecipherable gibberish. If I remove it everything seems to work fine.

**Comment by benjamine** [comment]
where are you seeing that? can you provide a file+line number?

**Comment by TomDmitriev** [comment]
Sure, /public/build/jsondiffpatch-full.js, line 2161. encodeURI is also called in the same file, line 1306 but that one doesn't seem to influence the diff result.

**Comment by benjamine** [comment]
that's the full bundle, it includes google-diff-match-patch that line is part of it.
the format it uses for text diffs standard Unidiff at char level
https://code.google.com/p/google-diff-match-patch/wiki/Unidiff

**Comment by TomDmitriev** [comment]
I see. Thanks for clearing that out!
