### ISSUE TITLE
assertSame is not defined

### ISSUE THREAD

**Issue by svpe** [benjamine/jsondiffpatch#71]
When I use assertSame it doesn't work. I use it exactly as in the example code but assertSame is not defined. Could it be that I still need to include another library?

assertSame(delta, {
   "name":["Argentina","Republica Argentina"], // old value, new value
    "population":["41324992"], // new value
    "capital":["Buenos Aires", 0, 0] // deleted
 });

**Comment by benjamine** [comment]
right, I just used it code snippets to say "this is object is like this",
if you want such a function you can use lodash [isEqual](https://lodash.com/docs#isEqual), or you could achieve the same (but probably more costly) with jsondiffpatch using `jsondiffpatch.diff(a, b) === undefined`
