### ISSUE TITLE
Using with angularjs

### ISSUE THREAD

**Issue by germanger** [benjamine/jsondiffpatch#77]
Is there a recommendation on how to properly use `jsondiffpatch` in angularjs?

**Comment by enkodellc** [comment]
I have it working in my angularJS just fine.
include the jsondiffpatch js and in your controller inject $window 

```
      var jsondiffpatch = $window.jsondiffpatch;
      var jsonDiff = jsondiffpatch.create({
        objectHash: function(obj) {
          if (typeof obj._id !== 'undefined') {
            return obj._id;
          }
          if (typeof obj.id !== 'undefined') {
            return obj._id;
          }
          if (typeof obj.name !== 'undefined') {
            return obj.name;
          }
          return JSON.stringify(obj);
        },
        arrays: {
          detectMove: true,
          includeValueOnMove: false
        },
        textDiff: {
          minLength: 60
        }
      });

   var delta = jsondiffpatch.diff(prepareForDiff(orig), prepareForDiff(new));

```

**Comment by germanger** [comment]
Great!

**Comment by germanger** [comment]
This worked great!
I was able to pass to the view the `delta` object, through the `scope`, like this:

    $scope.delta = jsondiffpatch.diff($scope.before, $scope.after);

But... I also want to pass to the view the prettified html. I'm trying like this:

    $scope.beautifulHtml = jsondiffpatch.formatters.html.format(delta, {a: 3, b: 4});

But I'm getting: `Cannot read property 'html' of undefined`, so I guess `formatters` is not available.

Any help?

**Comment by enkodellc** [comment]
Make sure you included all the necessary files:

```
<link rel="stylesheet" href="/bower_components/jsondiffpatch/public/formatters-styles/annotated.css">
<link rel="stylesheet" href="/bower_components/jsondiffpatch/public/formatters-styles/html.css">
<script type="text/javascript" src="/bower_components/jsondiffpatch/public/build/jsondiffpatch.min.js"></script>
<script type="text/javascript" src="/bower_components/jsondiffpatch/public/build/jsondiffpatch-formatters.min.js"></script>
```

**Comment by germanger** [comment]
Thank you!, indeed I only was including the `bower` "main file": `public/build/jsondiffpatch.js`. I'm now including `public/build/jsondiffpatch-formatters.js` too, (...and the styles)

**Comment by benjamine** [comment]
thanks @enkodellc !
@germanger I'm not sure what is the effect of that change in bower.json, would that make those files get included in client apps by default? because I would like to avoid that, as I suppose most client apps might be only interested in diffing.
I'm not sure if bower has something to declare optional files to include.

**Comment by germanger** [comment]
"would that make those files get included in client apps by default?"

Yes... for example there is a `Grunt` plugin called `bower_concat`, which concatenates all the mains of each library inside the directory `/bower_components`.

     "because I would like to avoid that, as I suppose most client apps might be only interested in diffing."

Ah, okay.<br>
Anyway, `bower_concat` lets you specify more mainFiles easily, if anyone reading is interested:

        bower_concat: {
            all: {
                dest: 'build/bower-concat.js',
                cssDest: 'build/bower-concat.css',
                mainFiles: {
                    'jsondiffpatch': ['public/build/jsondiffpatch.js', 'public/build/jsondiffpatch-formatters.js', 'public/formatters-styles/html.css', 'public/formatters-styles/annotated.css',]
                },
                bowerOptions: {
                    relative: false
                }
            }
        },

**Comment by sjoerd222888** [comment]
When you work angularJS is there a way to ignore the $$hashKey property? AngularJS adds this property apparently sometimes to track changes:
http://stackoverflow.com/questions/18826320/what-is-the-hashkey-added-to-my-json-stringify-result

Maybe the question can be put more general whether it is possible to ignore certain properties, but I put it here because in my case it's also specific to AngularJS.

**Comment by enkodellc** [comment]
Ignoring a property is a requested feature but it doesn't look like it was implemented. I delete properties using a temp object... I did not run into any $$hashkey properties.

https://github.com/benjamine/jsondiffpatch/issues/10

**Comment by benjamine** [comment]
thanks, yes,  this is not implemented out-of-the-box, and it's probably a good idea to add a function to filter properties right on the config object.
But you could achieve this writing a plugin: https://github.com/benjamine/jsondiffpatch/blob/master/docs/plugins.md 
unfortunately that might not be as deeply document as I'd like, so here's an example that might work for you:

``` js
var diffpatcher = jsondiffpatch.create();

// insert a new diff filter, right before "objects" one
diffpatcher.processor.pipes.diff.before('objects', objectPropertyTrimFilter);

function trimObject(obj) {
  trimmedObject = {};
  for (var name in obj) {
    if (name.slice(0, 2) !== '$$') {
      trimmedObject[name] = obj[name];
    }
  }
  return trimmedObject;
}

function objectPropertyTrimFilter(context) {
  if (!context.leftIsArray && context.leftType === 'object') {
    // replace context left object with trimmed version
    context.left = trimObject(context.left);
  }
  if (!context.rightIsArray && context.rightType === 'object') {
    // replace context right object with trimmed version
    context.right = trimObject(context.right);
  }
}


// use your diffpatcher
left = { a: 1, $$key: 4 };
right = { a: 3, $$key: 6 };
diffpatcher.diff(left, right);
```

**Comment by benjamine** [comment]
ps: a config option that affects the behavior of the [objects built-in filter](https://github.com/benjamine/jsondiffpatch/blob/master/src/filters/nested.js#L33) would be more performant, but a plugin is the available option right now.

**Comment by sansjunk** [comment]
@sjoerd222888 I ran into the same issue and worked around it by supplying angular another unique property to track with (using `track by`) thereby preventing the insertion of `$$hashkey`. This worked in my case since I had one such property. YMMV.

**Comment by enkodellc** [comment]
@sjoerd222888 nice catch: https://docs.angularjs.org/api/ng/directive/ngRepeat - works if your ngrepeat has an index.

**Comment by benjamine** [comment]
for simplicity, I added support for a `propertyFilter(name, context)` option, that would let you ignore properties either by name, or by any other test of the context left or right objects (see https://github.com/benjamine/jsondiffpatch#options ). I think with this is enough to close this issue, let me know otherwise.

**Comment by SidSyrus** [comment]
Hey @enkodellc , I'm trying with your solution. However it doesn't seem to work for me. Here's a [plunker](https://plnkr.co/edit/JlgIXFS3IE6sdQd1ikLK?) for it. Am I missing something here? Because if I do **jsondiffpatch.create** method, it creates a new jsondiffpatch object which in turns looses the **.formatters** function.
