### ISSUE TITLE
Diff ignoring array order changes 

### ISSUE THREAD

**Issue by mikenorgate** [benjamine/jsondiffpatch#79]
Is there an option to ignore changes in array order when doing a diff. For my application I want to diff two objects containing arrays but do not consider a change in order as a difference

**Comment by benjamine** [comment]
yes, what you have to specify 2 things:
- a function to identify each item in the array (eg. a function that return an item id, or any other type of key), so they can be matched regardless of their position (if you don't they get matched by position by default)
- indicate to ignore array moves

``` js
    var diffpatcher = jsondiffpatch.create({
        objectHash: function(obj) {
            return obj.id;
        },
        arrays: {
            detectMove: false
        }
    });
    diffpatcher.diff(left, right);
```

**Comment by mayukhdas2k15** [comment]
I have two arrays, 

    json1 = '[{"abc": "abc"}]';
    json2 = '[{"bcd": "bcd"}, {"abc": "abc"}]';

I want to show the diff as only bcd is added,
But after disabling the detectMove, I am getting the delta as

    {"0":[{"bcd":"bcd"}],"1":[{"abc":"abc"}],"_t":"a","_0":[{"abc":"abc"},0,0]}

From this response, how to interpret that only bcd has been added,
Have used the below:

    var diffpatcher = jsondiffpatch.create({
        objectHash: function(obj, index) {
            return obj.id || obj.id || obj.name;
        },
        arrays: {
            detectMove: false
        }
});

**Comment by daddybh** [comment]
hi  @benjamine, Is there any way to make diff result return `undefined` if the array was reordered?
Instead of returning:

```
{
    "_t": "a",
    "_4": [
        "",
        1,
        3
    ],
    "_5": [
        "",
        2,
        3
    ]
}
```

**Comment by benjamine** [comment]
@daddybh there is no out-of-the-box options flag, but I can think in 2 ways:

don't use `detectMove: false`, let it detect moves, and then post-process the diff, recursively removing any member where `Array.isArray(value) && value[2] === 3)`,
or write a jsondiffpatch plugin that does the same internally https://github.com/benjamine/jsondiffpatch/blob/master/docs/plugins.md , this is more elegant, but more complicated, I suppose probably not worth it for that case.

**Comment by daddybh** [comment]
Thanks @benjamine, I did notice the plugin feature, but had not idea how to do that.
For now, remove the moved delta would work, since I just need to compare two objects.

Is there any change to have an option for loose diff or some kind of `compare` api  :)
It will be very useful for unit testing when doing compare Objects, REST API response etc.

**Comment by benjamine** [comment]
@daddybh sure, not sure what a loose diff would look like, but open a separate issue with that idea, and I or someone else can give it a try 👍  (it's hacktoberfest :) )

**Comment by nonoroazoro** [comment]
@benjamine  Thanks to your tips, it works quite well.
