### ISSUE TITLE
missing gulpfile after bower install 

### ISSUE THREAD

**Issue by episodeyang** [benjamine/jsondiffpatch#82]
After 
```bash
bower install jsondiffpatch
```

and run 
```bash
make
```

it shows 
```bash
missing gulpfile
```

**Comment by benjamine** [comment]
this is intentional, bower dependencies are not intended to be built, as bower doesn't allow a postinstall step. 
In other words if you install it with bower, you don't need to `make` it, all the built bundles should be already included in the package.
