### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ukilon-okta** [benjamine/jsondiffpatch#87]
I am a little confused about what license is the software available under.
I could find https://github.com/benjamine/jsondiffpatch/blob/master/MIT-LICENSE.txt which suggests MIT, but the comment inside https://github.com/benjamine/jsondiffpatch/blob/master/public/build/jsondiffpatch-full.js suggests Apache 2. 
Could you please clarify?

**Comment by benjamine** [comment]
it's MIT.
the Apache license you see inside the bundle is from google's Diff Match Patch lib (included in the full bundle).
If that becomes a problem for your project you can always opt-out for that lib (using the regular bundle) and you just loose text (long strings) diff efficiency, but everything should just work.
