### ISSUE TITLE
Use jsondiffpatch outside node.js. Provide single build file.

### ISSUE THREAD

**Issue by sjoerd222888** [benjamine/jsondiffpatch#89]
I am looking for a single file to download and use outside the node.js ecosystem.

If it already exists, I am sorry that I could not find it immediatly, could you please add a hint to your documentation?

**Comment by fiatjaf** [comment]
Look at the files that are included in [the demo](http://benjamine.github.io/jsondiffpatch/demo/index.html):

```html
  <script type='text/javascript' src='../build/jsondiffpatch.min.js'>
  </script>
  <script type='text/javascript' src='../build/jsondiffpatch-formatters.min.js'>
  </script>
  <script type='text/javascript' src='../external/diff_match_patch_uncompressed.js'>
  </script>
```

They are [here](https://github.com/benjamine/jsondiffpatch/tree/gh-pages/build) and [here](https://github.com/benjamine/jsondiffpatch/tree/gh-pages/external).

**Comment by sjoerd222888** [comment]
Thanks. Are there also non-minified builds?

**Comment by sjoerd222888** [comment]
Thank you very much :-). What does 'gh-pages' stand for? Why do the build files exist in this branch and not in master?

**Comment by fiatjaf** [comment]
"gh-pages" is a special branch that, for every repository, GitHub turns into static websites served at `http://<user_name>.github.io/<repo_name>/`. This repository has a "gh-pages" branch which contains [this demo page](http://benjamine.github.io/jsondiffpatch/demo/index.html) at http://benjamine.github.io/jsondiffpatch/demo/index.html.

**Comment by benjamine** [comment]
hi, those bundles exist on master too, but on the /public folder: https://github.com/benjamine/jsondiffpatch/tree/master/public/build
as @fiatjaf mentioned gh-pages branch is for github static web hosting, thanks!

**Comment by sjoerd222888** [comment]
Thanks!
