### ISSUE TITLE
HTML escaping

### ISSUE THREAD

**Issue by molerat619** [benjamine/jsondiffpatch#93]
Hi,

I am using jsondiffpatch for my history module. For testing, I entered `<script type="text/javascript">window.alert("test");</script>` into a field and saved it. When I look at my history, that I display with jsondiffpatch, the html is not being escaped and I get the alert!

Is this how it really should work or is it a bug?

Best regards

**Comment by benjamine** [comment]
thanks, yes, I think it was identified and there's a patch, I just need to review it/ test it, should be fixed soon

**Comment by benjamine** [comment]
fixed in jsondiffpatch@0.1.36
