### ISSUE TITLE
Clear array

### ISSUE THREAD

**Issue by sjoerd222888** [benjamine/jsondiffpatch#94]
I have tested how array clears are handled. It seems that the delta basically contains a remove statement for every item. Is this correct or is my result wrong?

Wouldn't it be easier to have a more simpler single delta statement?

The code I used for testing:

    //Test array diff
    collectionOld = [
        "Astronomy",
        "Cosmology",
        "General Relativity",
        "Quantum Field Theories",
    ]
    collectionNew = [    ]	
    var delta  = jsondiffpatch.diff(collectionOld, collectionNew);
    console.log(delta);
    jsondiffpatch.patch(collectionOld, delta);
    console.log(collectionOld);

**Comment by benjamine** [comment]
I think current behavior better supports most general scenarios, the idea is having the removed items would let custom implementations do things like:
- logging or any type of audit/event notifications
- merge conflicts (eg. someone removing all + someone else modifiying or adding others)

If in a particular case you need a small payload (eg. to save memory/network traffic), that can be easily implemented as a refinement step (just going thru the delta and replacing these cases with something else), or, more elegantly, writting a jsondiffpatch [plugin](https://github.com/benjamine/jsondiffpatch/blob/master/docs/plugins.md)
