### ISSUE TITLE
Print to console

### ISSUE THREAD

**Issue by Vanuan** [benjamine/jsondiffpatch#97]
Is there a pretty printer that outputs delta on terminal?

**Comment by benjamine** [comment]
yes, using the `jsondiffpatch` binary, check the bottom of README:
https://github.com/benjamine/jsondiffpatch#console

if you want to do it programmatically, you can check the source here:
https://github.com/benjamine/jsondiffpatch/blob/master/bin/jsondiffpatch

**Comment by Vanuan** [comment]
Thanks
