### ISSUE TITLE
Is there any way of comparing more than two JSONs?

### ISSUE THREAD

**Issue by lipecg** [benjamine/jsondiffpatch#98]
I'm working on a version control for a system and jsondiffpatch already helps me a LOT (Thank you very much for that!!), but now my managers want a way to see the "history" of a JSON object and compare their N versions.

**Comment by benjamine** [comment]
thanks, I'm glad to hear that!
regarding the comparison, I'm not sure I understand the feature, can you provide an example of the expected behavior (input and output)?

**Comment by lipecg** [comment]
Hey, thanks for the prompt response!

Right, let me try and explain more clearly. So, our API has some sort of
version control where every time we save an object, it keeps the tracking
of the values. So we can do a GET and ask for an specific version and it
will return us a JSON with the object state at that version.

Currently we compare two versions as "left" and "right". But instead they
want me to make the system able to compare more than one version, so I
would need to provide something like an array with the objects and return
the differences between them.

What they are requesting me to do would be something like this:

This is what we do now:
var left = { name: 'some json' };
var right = { name: 'some different json' };
var delta = instance.diff(left, right);

I would need to call something like this:

var obj1 = { name: 'some json version 1' };
var obj2 = { name: 'some json version 2' }
var objN = { name: 'some json version N' };
var arrayObjects = [ obj1, obj2, objN ];

var delta = instance.diff(arrayObjects);

And as a result, it would be pretty much the same thing, except that
instead of oldValue, newValue, I would need to return N values, something
like:

delta = {
    "name" : [
        'some json version 1',
        'some json version 2',
        'some json version N'
    ]
};

Maybe there's already some way to do it and I just couldn't figure it out
in the meantime I'm trying to implement something similar to this using the
tool. I'm open to suggestions :)

Thanks again for your time. Really appreciate it!
Cheers,
Felipe



*Felipe Gonçalves*
lipecg@gmail.com
+1 (416) 460 1445

**Comment by benjamine** [comment]
Sorry but I still don't understand the use case, or what a comparison between multiple versions is.
I don't see a similar concept in the version control systems I know, how would you create a diff for N versions of a file in git for example?
maybe what you need is the delta between each consecutive version?
what's the output you would expect for this list of versions?
```
version[0] = { a: 1, b: { c: 3, d: 'hello' }, e: [ 2, 4, 5] };
version[1] = { a: 1, b: 4, d: 10, e: [ 2, 5] };
version[2] = { a: 1, b: { c: 14 }, d: 'world' };
version[3] = { a: 2, b: { c: 3 }, d: 'world', e: [ 4, 5] };
```
