### ISSUE TITLE
Large Amounts of Data

### ISSUE THREAD

**Issue by iamaaron** [benjamine/jsondiffpatch#99]
Anyone having any issues when comparing large amounts of data? It seems to crash my browser and takes quite a while to respond when comparing two large amounts of data in the HTML format (delta).

But then again, I have implemented with AngularJS. See implementation:

```javascript
var jsondiffpatch = $window.jsondiffpatch;

var delta = jsondiffpatch.diff($scope.firstSelection.data, $scope.secondSelection.data);

$scope.beautifulHtml = jsondiffpatch.formatters.html.format(delta);
```

```html
<section ng-bind-html="::beautifulHtml"></section>
```

For those who don't know, the two colons in front of beatuifulHtml via the view is single-way data binding.

**Comment by benjamine** [comment]
hi, I would like to have benchmarks but there's none yet, can you provide samples of large data?
so I can estimate if the performance cost is reasonable or there are optimizations that can be done.
